#!/bin/bash
# passwords
KEYSTORE_PASSWORD=$(awk -F'"' '/keyStorePassword/ { print $4 }' /opt/nifi-certificates/tls.json)
TRUSTSTORE_PASSWORD=$(awk -F'"' '/trustStorePassword/ { print $4 }' /opt/nifi-certificates/tls.json)

# set in nifi.properties
sed -i -e "s#^nifi.security.keystorePasswd.*#nifi.security.keystorePasswd=$KEYSTORE_PASSWORD#" /opt/nifi/conf/nifi.properties
sed -i -e "s#^nifi.security.keyPasswd.*#nifi.security.keyPasswd=$KEYSTORE_PASSWORD#" /opt/nifi/conf/nifi.properties
sed -i -e "s#^nifi.security.truststorePasswd.*#nifi.security.truststorePasswd=$TRUSTSTORE_PASSWORD#" /opt/nifi/conf/nifi.properties
