#!/bin/bash
# set JAVA_HOME
export JAVA_HOME=/usr/lib/jvm/jre

# run toolkit server briefly to generate conf
/opt/nifi-toolkit/bin/tls-toolkit.sh server -a RSA -c {{ ansible_hostname }} -d 3650 -D "CN={{ ansible_hostname }},OU=nifi" -f /opt/nifi-ca-certificates/tls.json -k 2048 -p 8443 -s SHA256WITHRSA -T jks -t {{ keystore_password }} &

# capture pid
TOOLKIT_PID=$!

# sleep a moment, then kill the toolkit server instance
sleep 5 && kill $TOOLKIT_PID
