#!/bin/bash
# Adds proxy request permission to node from cluster
export JAVA_HOME=/usr/lib/jvm/default-java

# various vars - the curl to 169.254.169.254 are AWS instance-specific API facts
CLUSTERJSON=$(mktemp)
S3BUCKET=$(cat /opt/nifi-conf/bucket)

# Retries
MAX_ATTEMPTS=3
SLEEP_INTERVAL=35
TARGET_STATE="COMPLETE"

# List nodes
LIST_ATTEMPTS=1
LIST_STATE="INCOMPLETE"
while [[ $LIST_ATTEMPTS -le $MAX_ATTEMPTS && $LIST_STATE != $TARGET_STATE ]]
do
  # List nodes in json
  /opt/nifi-toolkit/bin/cli.sh nifi list-users -p /opt/nifi-certificates/admin/cli.properties -ot json > $CLUSTERJSON
  cat $CLUSTERJSON | grep --quiet $(hostname)
  if [ $? -eq 0 ]
  then
    LIST_STATE="COMPLETE"
  else
    LIST_ATTEMPTS=$(($LIST_ATTEMPTS+1))
    sleep $SLEEP_INTERVAL
  fi
done

# NODEID from HOSTNAME using jq
NODEID_ATTEMPTS=1
NODEID_STATE="INCOMPLETE"
while [[ $NODEID_ATTEMPTS -le $MAX_ATTEMPTS && $NODEID_STATE != $TARGET_STATE ]]
do
  NODEID=$(jq -r '.users[].component | select(.identity | contains("'$(hostname)'")).id' $CLUSTERJSON)
  echo $NODEID | grep --quiet '.*-.*-.*-.*-.*'
  if [ $? -eq 0 ]
  then
    NODEID_STATE="COMPLETE"
  else
    NODEID_ATTEMPTS=$(($NODEID_ATTEMPTS+1))
    sleep $SLEEP_INTERVAL
  fi
done

# Extract admin key and cert
export GENERATED_PASSWORD=$(cat /opt/nifi-conf/generated_password)
cd /opt/nifi-certificates/admin/
openssl pkcs12 -in keystore.p12 -nodes -nocerts -out private_key.pem -passin file:/opt/nifi-conf/generated_password
openssl pkcs12 -in keystore.p12 -nokeys -out admin_cert.pem -passin file:/opt/nifi-conf/generated_password

# Policy ID
POLICYUP_ATTEMPTS=1
POLICYUP_STATE="INCOMPLETE"
while [[ $POLICYUP_ATTEMPTS -le $MAX_ATTEMPTS && $POLICYUP_STATE != $TARGET_STATE ]]
do
  POLICYID=$(curl --silent 'https://{{ lb_dns }}:{{ web_port }}/nifi-api/policies/write/proxy' --insecure --key /opt/nifi-certificates/admin/private_key.pem --cert /opt/nifi-certificates/admin/admin_cert.pem | jq -r '.component.id')
  # Use current policy to build new policy with NODEID
  curl --silent 'https://{{ lb_dns }}:{{ web_port }}/nifi-api/policies/write/proxy' --insecure --key /opt/nifi-certificates/admin/private_key.pem --cert /opt/nifi-certificates/admin/admin_cert.pem | \
jq '.component.users += [{"revision": { "version": 0 }, "id": "'$NODEID'","permissions": {"canRead": true,"canWrite": true},"component": {"id": "'$NODEID'", "identity": "CN='$(hostname -f)', OU=NIFI","configurable": true} }]' | \
curl -X PUT 'https://{{ lb_dns }}:{{ web_port }}/nifi-api/policies/'$POLICYID'' --insecure --key /opt/nifi-certificates/admin/private_key.pem --cert /opt/nifi-certificates/admin/admin_cert.pem -H 'Content-Type: application/json' --data @-
  if [ $? -eq 0 ]
  then
    POLICYUP_STATE="COMPLETE"
  else
    POLICYUP_ATTEMPTS=$((POLICYUP_ATTEMPTS+1))
    sleep $SLEEP_INTERVAL
  fi
done

# Cleanup
rm -f $CLUSTERJSON /opt/nifi-certificates/admin/private_key.pem /opt/nifi-certificates/admin/admin_cert.pem
