#!/bin/bash
# Gracefully exits node from cluster
export JAVA_HOME=/usr/lib/jvm/default-java
HOOKRESULT='CONTINUE'
REGION=$(curl -s 169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/.$//')
INSTANCEID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
CLUSTERJSON=$(mktemp)

# Ensure awscli installed
/usr/bin/pip install awscli

# LIST
/opt/nifi-toolkit/bin/cli.sh nifi get-nodes -p /mnt/nifi/admin-certificates/cli.properties -ot json > $CLUSTERJSON

# NODEID from HOSTNAME
NODEID=$(jq -r '.cluster[] | map(select(.address | contains("'$(hostname)'")).nodeId) | @tsv' $CLUSTERJSON)
rm -f $CLUSTERJSON
echo "$(date) NODEID $NODEID"

# DISCONNECT
/opt/nifi-toolkit/bin/cli.sh nifi disconnect-node --nifiNodeId $NODEID -p /mnt/nifi/admin-certificates/cli.properties

# OFFLOAD after DISCONNECTED
while true
do
  /opt/nifi-toolkit/bin/cli.sh nifi get-node --nifiNodeId $NODEID -p /mnt/nifi/admin-certificates/cli.properties | grep --quiet DISCONNECTED
  if [ $? -eq 0 ]
  then
    echo "$(date) DISCONNECTED, OFFLOADING"
    /opt/nifi-toolkit/bin/cli.sh nifi offload-node --nifiNodeId $NODEID -p /mnt/nifi/admin-certificates/cli.properties
    break
  else
    sleep 2
  fi
done

# place DELETE after OFFLOADED
while true
do
  /opt/nifi-toolkit/bin/cli.sh nifi get-node --nifiNodeId $NODEID -p /mnt/nifi/admin-certificates/cli.properties | grep --quiet OFFLOADED
  if [ $? -eq 0 ]
  then
  echo "$(date) OFFLOADED, placing DELETE note"
    touch /mnt/nifi/cluster/leave/$NODEID
    break
  else
    sleep 2
  fi
done

# notify lifecycle hook
/usr/local/bin/aws autoscaling complete-lifecycle-action --lifecycle-hook-name $LIFECYCLEHOOKNAME --auto-scaling-group-name $ASGNAME --lifecycle-action-result $HOOKRESULT --instance-id $INSTANCEID --region $REGION

# remove temp file
rm -f $CLUSTERJSON
